import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e3e2df",
        "primary": "#000000",
        "on-surface-variant": "#4d4540",
        "on-secondary-fixed-variant": "#4a4643",
        "secondary-fixed": "#e8e1dd",
        "error": "#ba1a1a",
        "outline-variant": "#d0c4be",
        "secondary": "#625d5a",
        "primary-fixed": "#e9e1dd",
        "on-tertiary-fixed": "#141d21",
        "surface-container-low": "#f4f3f0",
        "tertiary-fixed": "#dbe4ea",
        "on-primary-fixed-variant": "#4a4643",
        "on-primary-fixed": "#1e1b19",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#bfc8ce",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#efeeeb",
        "surface-tint": "#625d5b",
        "tertiary": "#000000",
        "background": "#faf9f6",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#7c858b",
        "surface-dim": "#dbdad7",
        "error-container": "#ffdad6",
        "primary-container": "#1e1b19",
        "secondary-container": "#e6deda",
        "on-secondary": "#ffffff",
        "surface": "#faf9f6",
        "on-secondary-container": "#66625e",
        "on-primary-container": "#888380",
        "inverse-surface": "#2f312f",
        "outline": "#7e7570",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#ccc5c1",
        "surface-variant": "#e3e2df",
        "inverse-primary": "#ccc5c2",
        "tertiary-container": "#141d21",
        "inverse-on-surface": "#f2f1ee",
        "surface-bright": "#faf9f6",
        "on-surface": "#1a1c1a",
        "primary-fixed-dim": "#ccc5c2",
        "on-secondary-fixed": "#1e1b19",
        "on-background": "#1a1c1a",
        "surface-container-high": "#e9e8e5",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#3f484d"
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-space-grotesk)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      typography: {
        stone: {
          css: {
            "--tw-prose-body": "#1a1c1a",
            "--tw-prose-headings": "#1a1c1a",
            "--tw-prose-lead": "#4d4540",
            "--tw-prose-links": "#1a1c1a",
            "--tw-prose-bold": "#1a1c1a",
            "--tw-prose-counters": "#1a1c1a",
            "--tw-prose-bullets": "#1a1c1a",
            "--tw-prose-hr": "#e9e8e5",
            "--tw-prose-quotes": "#1a1c1a",
            "--tw-prose-quote-borders": "#ccc5c2",
            "--tw-prose-captions": "#4d4540",
            "--tw-prose-code": "#1a1c1a",
            "--tw-prose-pre-code": "#e9e8e5",
            "--tw-prose-pre-bg": "#2f312f",
            "--tw-prose-th-borders": "#ccc5c2",
            "--tw-prose-td-borders": "#e9e8e5",
          },
        },
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};

export default config;
